app:
    resource: '@UserApiBundle/Controller/'
    type: annotation
json_api_routes:
    prefix: /api/db
    resource: .
    type: json_api
route1:
    path:     /{path}
    defaults: { _controller: UserApiBundle:Default:directToAngular }
    requirements: { path: “(?!api).+” }