<?php

namespace UserApiBundle\Repository;

/**
 * BuildingFloorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuildingFloorRepository extends \Doctrine\ORM\EntityRepository
{



}
