<?php

namespace UserApiBundle\Repository;

/**
 * BuildingSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloorSectionRepository extends \Doctrine\ORM\EntityRepository
{
}
