<?php

namespace UserApiBundle\Repository;
use UserApiBundle\Entity\BuildingFloor;
use UserApiBundle\Entity\Issue;

/**
 * IssueSubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FloorSubscriptionRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param BuildingFloor $floor
     * @return array
     */
    public function getSubscriptionsByFloor(BuildingFloor $floor){
        return $this->findBy(array(
            'floor' => $floor->getId()
        ));
    }
}
