<?php

namespace UserApiBundle\Repository;

/**
 * IssueStateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueStateRepository extends \Doctrine\ORM\EntityRepository
{
}
