<?php

namespace UserApiBundle\Repository;

/**
 * IssueCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssueCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
