<?php

namespace UserApiBundle\Repository;

/**
 * IssuePriorityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IssuePriorityRepository extends \Doctrine\ORM\EntityRepository
{
}
